backend:
  name: github
  repo: tvegis/my-blog
  branch: main
  base_url: https://tvegis-blog.vercel.app
  auth_endpoint: /api/auth

media_folder: "public/images"
public_folder: "/images"

collections:
  - name: "posts"
    label: "Blog Posts"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    extension: mdx
    format: frontmatter
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Tags", name: "tags", widget: "list", default: [] }
      - { label: "Cover Image", name: "cover", widget: "image", required: false }
      - { label: "Draft", name: "draft", widget: "boolean", default: true }
      - { label: "Body", name: "body", widget: "markdown" }
